stages:
  - build
  - test

build:
  stage: build
  image: maven:3.8.1-openjdk-17-slim
  script:
    - export NEW_VERSION=${CI_COMMIT_SHA:0:8}-${CI_COMMIT_REF_NAME}
    - mvn versions:set -DnewVersion=1-$NEW_VERSION
    - mvn -s ci_settings.xml deploy
  only:
    - qa
    - main

unit-test-job:
  image: maven:3.8.4-openjdk-17-slim
  stage: test
  script:
    - echo "Running unit tests…"
    - mvn test

sonarcloud-check:
  image: maven:3.8.1-openjdk-17-slim
  stage: test
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    - mvn verify sonar:sonar -Dsonar.projectKey=team114934837_gps_g11
